on:
  workflow_call:
    inputs:
      target:
        type: string
        default: default
        description: 'Bake target to build'
      permit-login:
        type: boolean
        default: false
        description: 'Permit login to container registry'
      permit-push:
        type: boolean
        default: false
        description: 'Permit pushing built images to container registry'
      permit-cache:
        type: boolean
        default: false
        description: 'Permit using GitHub Actions cache for buildx'
    secrets:
      MAXMINDDB_USER_ID:
        required: true
        description: 'User ID for MaxMind GeoIP databases'
      MAXMINDDB_LICENSE_KEY:
        required: true
        description: 'License key for MaxMind GeoIP databases'

env:
  MAXMINDDB_USER_ID: ${{ secrets.MAXMINDDB_USER_ID }}
  MAXMINDDB_LICENSE_KEY: ${{ secrets.MAXMINDDB_LICENSE_KEY }}

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate Docker metadata
        id: docker-meta
        uses: docker/metadata-action@v5

      - name: Generate GitHub metadata
        id: github-meta
        uses: dockerbakery/github-metadata-action@v4

      - if: ${{ inputs.permit-login }}
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/bake-action@v6
        with:
          targets: ${{ inputs.target }}
          push: ${{ inputs.permit-push }}
          files: |
            ./docker-bake.hcl
            ./${{ inputs.target }}/docker-bake.hcl
            cwd://${{ steps.docker-meta.outputs.bake-file-labels }}
            cwd://${{ steps.docker-meta.outputs.bake-file-annotations }}
            cwd://${{ steps.github-meta.outputs.bake-file }}
          set: |
            ${{ inputs.permit-cache && '*.cache-from=type=gha' || ''}}
            ${{ inputs.permit-cache && '*.cache-to=type=gha,mode=max' || ''}}
